info:
  contact: {}
paths:
  /upload_file:
    post:
      consumes:
      - multipart/form-data
      description: upload a file to encrypt
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Server operations
  /upload_key:
    post:
      consumes:
      - multipart/form-data
      description: uploads a public key
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Server operations
swagger: "2.0"
