basePath: /
info:
  contact: {}
  description: Server Operations
  title: Server API
  version: 1.0.0
paths:
  /encryption/decrypt_file:
    post:
      description: Provide the filename to decrypt
      parameters:
      - description: Filename to decrypt
        in: formData
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: file_decrypted
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Decrypt a file
      tags:
      - Encryption
  /encryption/saved_file:
    post:
      consumes:
      - multipart/form-data
      description: Save a file to encrypt
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_saved
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Save file
      tags:
      - Encryption
  /encryption/upload_file:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to encrypt
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_uploaded
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Upload file
      tags:
      - Encryption
  /encryption/upload_key:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a public key
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: key_uploaded
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Upload key
      tags:
      - Encryption
swagger: "2.0"
